# Generated by Django 4.2 on 2023-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='banner',
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.ManyToManyField(blank=True, to='pages.banner'),
        ),
    ]
