# Generated by Django 4.2 on 2023-05-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_banner_page_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='banner',
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.banner'),
        ),
    ]
