# Generated by Django 4.2 on 2023-04-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('img', models.ImageField(blank=True, null=True, upload_to='items/img/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='items/img/', verbose_name='Изображение')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('image_list', models.ManyToManyField(blank=True, to='images.image')),
            ],
        ),
    ]
